// <auto-generated />
namespace AgencyWebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class salestable_create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(salestable_create));
        
        string IMigrationMetadata.Id
        {
            get { return "202502261110558_salestable_create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
