// <auto-generated />
namespace AgencyWebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class projectdb_detaildb_editrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(projectdb_detaildb_editrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "202502201840352_projectdb_detaildb_editrelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
